### PR TITLE
Hotfix: preformatted strings on study table

### PR DESCRIPTION
**Pull request by rabstejnek**
### Before
image

### After
image

### CODE REVIEW

**Comment by rabstejnek** [comment]
@shapiromatron  Do you think this inline style fix is appropriate? We could instead make changes to the JS:
https://github.com/shapiromatron/hawc/blob/6d3fee1721509093893beda48f58293a0cdda12c/frontend/study/Study.js#L154
Maybe a third parameter, `preformatted: bool` ?

**Comment by shapiromatron** [comment]
> @shapiromatron Do you think this inline style fix is appropriate? We could instead make changes to the JS:
> https://github.com/shapiromatron/hawc/blob/6d3fee1721509093893beda48f58293a0cdda12c/frontend/study/Study.js#L154
> 
> 
> Maybe a third parameter, `preformatted: bool` ?

Yes, that or just a new `tbl.add_tbody_tr_pre` method; this jQuery stuff will be rewritten in the future

**Review by shapiromatron — APPROVED** [review]
@rabstejnek I ended up changing it to an option as you suggested

**Comment by shapiromatron** [comment]
@rabstejnek please review to make sure you like my change; since options already existed with this method, it made sense just to add another one instead of duplicated a complex method

**Pull request merged**
