### PR TITLE
Appdev 3805 allow null metric

### PR DESCRIPTION
**Pull request by jaybuie-cgi**
I created this pull request because I made a slight tweak to the code for ticket APPDEV-3805 while I was QAing it.

### CODE REVIEW

**Comment by shapiromatron** [comment]
this request is massive and covers lots of different areas, is there a way this can be broken up? @shanethacker - was this intended for hawc-prime?

**Comment by jaybuie-cgi** [comment]
Andy,



No, that was a mistake.  I meant to create a pull request to merge it with our team HERO "develop" branch.



This is my first time doing a branch/pull request/etc. in Git.  I apologize for this mistake.



Thank you,


Jay Buie | Senior Consultant | CGI Federal | (M) 843-902-9596



________________________________

**Comment by shapiromatron** [comment]
@jaybuie-cgi ahh, no problem. I like lots of whats in this PR, and would like to start receiving PRs from your team, just more bite-sized. @shanethacker, when might this be coming?

**Comment by shanethacker** [comment]
@shapiromatron I need to clean some of them up a bit and submit them. Not sure what happened on this one; looks like it ended up with all of the commits. :)

**Comment by shapiromatron** [comment]
please do; the longer it takes to get them submitted into upstream hawc the more difficult it will be to integrate.

**Comment by shanethacker** [comment]
Oh, wait, I get it. It tried to gather all the different commits that don't exist in HAWC Prime. That makes sense.

**Comment by jaybuie-cgi** [comment]
Yeah.  Again, this was me doing it wrong the first time.  I created a different pull request to merge it into where it needed to go -- our "develop" branch.

Sorry.

Jay Buie | Senior Consultant | CGI Federal | (M) 843-902-9596



________________________________

**Pull request closed without merging**
