### PR TITLE
assessment level database dump management command

### PR DESCRIPTION
**Pull request by shapiromatron**
Add `assessment_qs` commands for risk of bias module once the model API has stabilized.

### CODE REVIEW

**Comment by JoshAddington** [comment]
So, I tried importing Assessment 57 into a clean DB with just the migrations run, and no Animal Endpoints are being loaded into the DB. Epi and Invitro endpoints are loaded, but not Animal.

**Comment by shapiromatron** [comment]
@JoshAddington any errors?

**Comment by JoshAddington** [comment]
@shapiromatron No errors when running the management command

**Comment by shapiromatron** [comment]
ok, let me update this branch and resubmit

**Comment by shapiromatron** [comment]
@JoshAddington ok, i've made a few tweaks, though they're unrelated to the animal model exports. Can you try again, and see if it works better this time?

**Comment by JoshAddington** [comment]
Spent some time trying to hunt down what's going with the animal endpoints. They're in the .sql file that's generated, but for some reason the entries aren't being added to the animal_endpoint table. Couldn't say why, though.

Are the Risk of Bias reviews supposed to be exported as well?

**Comment by shapiromatron** [comment]
Hmm, I think we're on the danger-zone of "it works on my computer". Both animal endpoints and risk of bias reviews are included in the export, and they load fine for me in the db export. 

Are you seeing any errors when you run the command `psql -d hawc3 -f ~/Desktop/foo.sql`?

**Comment by JoshAddington** [comment]
If I don't run `python manage.py migrate` before the command, then the psql command runs fine, but I get errors running migrate after. If I run migrate first, then I get a bunch of
`multiple primary keys for table "xxx" not allowed`
and 
`insert or update on table "xxx" violates foreign key constraint "xxx", Key (xxx_id)=(ddd) is not present in table "xxx"`
errors

The data for both animal endpoints and risk of bias reviews are in the .sql file.

**Comment by shapiromatron** [comment]
What if you don't run migrate at all?

**Comment by JoshAddington** [comment]
It works if I don't migrate, but wouldn't that lock the models to the current model structure if I can't migrate?

**Comment by shapiromatron** [comment]
Yes, and I think that's fine-as is. The intended goal for this is a static, immutable export, which can be used in other database systems. It'd be nice if I could also add migrations to the export, but I didn't find an introspective way to do this.

**Comment by JoshAddington** [comment]
ok, then it LGTM

**Pull request merged**
