### PR TITLE
Copy data across assessments with management command

### PR DESCRIPTION
**Pull request by shapiromatron**
Copy data (bioassay, epi, or in-vitro) and optionally risk of bias across assays. Wrapped in a single transaction in case of failure. If RoB is copied, then metrics/domains are only created if they do not already existing in the target assessment.

### CODE REVIEW

**Comment by shapiromatron** [comment]
@JoshAddington I'm not seeing the experiments copy over now, did I inadvertently break this?

**Comment by JoshAddington** [comment]
@shapiromatron Yep, that's what caused the problem.

**Comment by JoshAddington** [comment]
Maybe Metric.metric should be renamed Metric.name, not necessarily in this PR. Most models use name where Metric is using metric. Might be a good idea for consistency.

**Comment by shapiromatron** [comment]
Agreed re: renaming `Metric.metric` to `Metric.name`; I'll add a trello card.

**Pull request merged**
